### ISSUE TITLE
update pypi wheel setup version

### ISSUE THREAD

**Issue by tungli** [rafguns/wosfile#10]
I used this package in my class and some students got the #4 issue.

My hypothesis is that for some users wheel install takes preference over the tarball, even if the version is older:
Look at [available packages on pypi](https://pypi.org/simple/wosfile/)

Do you know how and why this happens and possibly fix this? Thanks!

**Comment by tungli** [comment]
It seems the install of 0.4.2 fails on unicode in README.md due to quotes around `plain text` or the `TM` unicode.. possibly both or something else entirely... not sure since I cannot reproduce this.

**Comment by rafguns** [comment]
Thanks for the report! Which Python version are you (or your students) using?

**Comment by rafguns** [comment]
> It seems the install of 0.4.2 fails on unicode in README.md due to quotes around `plain text` or the `TM` unicode.. possibly both or something else entirely... not sure since I cannot reproduce this.

I suspect this is due to not specifying an encoding in https://github.com/rafguns/wosfile/blob/2c4b4d4672382c7e525fabdd620b8c09b806fa76/setup.py#L3

**Comment by tungli** [comment]
> I suspect this is due to not specifying an encoding in
> 
> https://github.com/rafguns/wosfile/blob/2c4b4d4672382c7e525fabdd620b8c09b806fa76/setup.py#L3

Probably yes. It was the line in the traceback during setup. The traceback then goes to `python\lib\encodings\cp1250.py`.
On my system (Linux) it does not crash, even if I specify the `'cp1250'` encoding... maybe it is Windows specific.

> Which Python version are you (or your students) using?

should be newest stable -- Python 3.9

**Comment by rafguns** [comment]
I cannot reprodue the crash on Windows but since it's a good idea anyway to specify the encoding, I pushed a commit to do that.

As for the pypi wheel, I'll move the CI (testing and deployment to pypi) to Github Actions. Once that's done (hopefully in the course of this week), I'll release the next version, which should install cleanly.

**Comment by rafguns** [comment]
I just released v0.5, with the encoding fix and a fix to ensure that we always publish both source and a wheel to pypi. Can you verify that this fixes the problem?

    pip install --upgrade wosfile

Thanks!

**Comment by rafguns** [comment]
Closing for now, since the issues mentioned (wheel and README encoding) have been resolved. Feel free to reopen or file a new issue if there's still some issue with installation.
