### ISSUE TITLE
Port test suite to pytest

### ISSUE THREAD

**Issue by rafguns** [rafguns/wosfile#2]
Nose has been [unmaintained for several years](https://nose.readthedocs.io/en/latest/). It makes sense to move the test suite to [pytest](http://pytest.org/).

**Comment by AminuBishir** [comment]
I'll like to contribute on this. But it seems the README is not descriptive enough, please try to, at least, show how can the project be ran (with a simple code snippet for running/processing data/record).

Thanks

**Comment by rafguns** [comment]
Thank you @AminuBishir ! Let me know here if you need any assistance.

I guess you're right about the README. I'll make a separate issue about that.

**Comment by AminuBishir** [comment]
Thank you @rafguns  for the response.
The assistance that I need here has to do with the **Usage** of the module. Like, after installation, how can one run it with a test data

**Comment by rafguns** [comment]
Fixed in 03572e1a39822ee3f4bb0f4b55552ce90f2d99db
